[variables]
PRISMA_SKIP_POSTINSTALL_GENERATE = "true"

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "DATABASE_URL=postgresql://dummy:dummy@localhost:5432/dummy npx prisma generate",
  "npm run build"
]
